### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by bissoligiulia** [lvgig/tubular#11]
The test tests/nominal/test_GroupRareLevelsTransformer.py::TestTransform::test_expected_output_no_weight fails.

This issue is to report and fix the problem on the mentioned test.

**Comment by bissoligiulia** [comment]
The problem is that the inplace parameter of Categorical.add_categories() is deprecated since version 1.3.0 of pandas

**Comment by nedwebster** [comment]
Issue is referenced in the following issue ticket: #12, closing this ticket as it will be resolved there.
