### ISSUE TITLE
Apply ruff rulse ANN flake8-annotations

### ISSUE THREAD

**Issue by davidhopkinson26** [lvgig/tubular#116]
https://beta.ruff.rs/docs/rules/#flake8-annotations-ann

make code compliant with rule set and then add to ruleset in .ruff.toml. If appropriate identify specific rules or parts of code to exclude.

2547 errors found for missing annotations.

This is a big one, happy to take contributions by module or individual script rather than addressing entire package in one go.

**Comment by adamsardar** [comment]
Closed by #128
