### ISSUE TITLE
remove develop branch

### ISSUE THREAD

**Issue by davidhopkinson26** [lvgig/tubular#136]
The main/ develop split adds a frustrating roadblock to development as it effectively requires doubling up of review on changes.  Would be much more straightforward to just merge feature branches straight into main and tag releases.  Possibly also creating release branches.

I think this may have implications for the documentation on readthedocs so need to investigate that before removing the develop branch.

**Comment by adamsardar** [comment]
I've come to learn that this style of development ('main+friends') is called [trunk-based development](https://trunkbaseddevelopment.com/).

I'm a fan of 'tag to release' as a model - [microsoft really like release branches](https://learn.microsoft.com/en-us/devops/develop/how-microsoft-develops-devops#differences-from-github-flow), but I believe that they also commit to patching critical bugs previous releases (hence causing the history to diverge), which we would never do for tubular - people should just update to a version with the bug patched. The release branches would effectively be save-game points on the journey through the commit history, which is exactly the same as tags.

**Comment by davidhopkinson26** [comment]
Thanks for the link.  I agree about tagging vs. release branches, no current plans to bugfix old releases.  Trunk based development with tagged releases seems like the way to go.  Will look to make this change after the next release.

**Comment by davidhopkinson26** [comment]
Changed pypi release process to trigger upon creating a release on github (which also creates a release tag) in #161.  Have now removed develop branch so we will use  [trunk-based development](https://trunkbaseddevelopment.com/) from main from now on.
