### ISSUE TITLE
Add type stubs to functions

### ISSUE THREAD

**Issue by adamsardar** [lvgig/tubular#137]
**What**

A [type stub](https://google.github.io/pytype/developers/type_stubs.html) is a file with a .pyi extension that describe a module’s types while omitting implementation details. Somewhat like a header file in C++ (?)

**Why**

People are moving towards employing greater type safety in their workflows: e.g. [mypy](https://mypy.readthedocs.io/en/stable/), [pyright ](https://github.com/microsoft/pyright) and - specific to this project - [type guard](https://typeguard.readthedocs.io/en/stable/userguide.html); see #128 and #120. Some of these projects are easier to use if type stubs for exported functions are made available.

**How**

Now that typehints are present (or shortly present? see #128) across tubular's codebase, some tools like [stubgen ](https://mypy.readthedocs.io/en/stable/stubgen.html) can create them automatically (if the docs are to be believed).

**Comment by davidhopkinson26** [comment]
Thanks for the suggestion @adamsardar.  

Have seen typestubs championed as a nice documentation of the user interface. I feel like in this case this would not be terribly useful as there is more context required to understand many arguments than just the argument name and type. This would require a user to check the docstring anyway (I suppose this is a sign that those names could be improved!)

It is also then a second source of truth to maintain and the docs of stubgen for instance suggest they will only produce a draft and manual refinements are required.

That said implementing greater type safety with typeguard or others as you say will be beneficial so will look into how type stubs might make that easier.  Just need to balance any benefit against the additional maintenance overhead the type stub files would add.
