### ISSUE TITLE
TwoColumnOperatorTransformer bugs

### ISSUE THREAD

**Issue by TommyMatthews** [lvgig/tubular#144]
Input check for columns needs fixing as it currently
- Does not raise a value error when instantiated with empty columns list
- Does not raise a type error when columns instantiated with a string

**Comment by ChaitanMohr** [comment]
An existing check grouped these two issues together with an and statement, so only raised a ValueError when both issues were happening. Split that up into two separate checks instead to raise a ValueError or TypeError.
