### ISSUE TITLE
CutTransformer test needs pandas>=1.1.0

### ISSUE THREAD

**Issue by shreenapatel** [lvgig/tubular#16]
One of the CutTransformer tests is incompatible with pandas<1.1.0:

tests/numeric/test_CutTransformer.py::TestTransform::test_expected_output

This will raise an error for older versions of pandas, which are missing the `ordered` argument in `pandas.cut`.

Could change the test or update version of pandas in requirements-dev.txt?

**Comment by richardangell** [comment]
this fix is in main with https://github.com/lvgig/tubular/pull/29
