### ISSUE TITLE
GitHub Codespaces requires contributor status to push

### ISSUE THREAD

**Issue by limlam96** [lvgig/tubular#172]
GitHub Codespaces requires contributor status to push, see image below. To replicate open tubular codespaces with non-contributor account, branch off of main and attempt push. Imagine this is a setting we can toggle

![image](https://github.com/lvgig/tubular/assets/103185696/976fccba-7619-44fb-8869-2a6c6412a63f)

**Comment by davidhopkinson26** [comment]
This is intentional.  At present external contributors need to create a fork and make a PR into this repo to contribute (e.g. #130).

We should probably make this clearer in [CONTRIBUTING.rst](https://github.com/lvgig/tubular/blob/main/CONTRIBUTING.rst)
