### ISSUE TITLE
[Bug]: OneHotEncodingTransformer no long compatible with sklearn

### ISSUE THREAD

**Issue by biggyfatty** [lvgig/tubular#186]
### What happened?

A bug happened!
'sparse' is renamed to 'sparse_output' in scikit-learn, believe tubular also need to make corresponding change

TypeError: __init__() got an unexpected keyword argument 'sparse' for OneHotEncodingTransformer 

### Environment

OS Name	Microsoft Windows Server 2019 Datacenter
Version	10.0.17763 Build 17763

python 3.9.18
tubular==1.2.1 (believe same issue still exists in 1.2.2)
scikit-learn==1.4.1post1

### Relevant error output

```shell
TypeError: __init__() got an unexpected keyword argument 'sparse' for OneHotEncodingTransformer
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adamsardar** [comment]
Related to #184: it isn't just `OneHotEncodingTransformer` that is affected. Could you see if the problem persists on py38?
