### ISSUE TITLE
Look for faster alternatives to DataFrame.drop 

### ISSUE THREAD

**Issue by limlam96** [lvgig/tubular#196]
What?
For e.g. LogTransformer, dropping the original column is one of the slower operations. Would be good to look into faster alternatives, e.g. df.columns.isin(wanted_columns)

Why?
Speed up tubular

How?
Explore alternatives to pd.DataFrame.drop, profile candidates to confirm efficiency benefits

**Comment by JagadishSivakumar** [comment]
That's a nice idea. The suggested alternative `df.columns.isin()`  is the `Boolean indexing` approach and is efficient compared to `df.drop()` which involves removing unwanted columns iteratively.

Another solution I can think of is a `df.filter()` used to subset the df according to the conditions in the labels. It's efficient and directly creates a new df with only desired columns without having to rearrange or drop data.

**Comment by Ritunjai-Sharma** [comment]
I've created a quick notebook to profile df.drop() as well as df.columns.isin() and df.filter() : https://github.com/lvgig/tubular/blob/196-look-for-faster-alternatives-to-dataframedrop/examples/profile_pd.fillna_alternatives.ipynb
It does seem that df.filter() is a bit quicker than the other two approaches

Let me know what you guys think!

**Comment by JagadishSivakumar** [comment]
Hi RJ, nice work. I just wanted to let you know that I tried a new method of dropping features using the `del` statement and its much faster than the other methods. I have added a new block to your notebook, so please take a look at it.

Results from latest run:
![Screenshot 2024-03-15 at 14 28 22](https://github.com/lvgig/tubular/assets/32516839/d8b8a3d2-b1ed-4fe9-9749-c6a11ca22a59)

https://github.com/lvgig/tubular/blob/196-look-for-faster-alternatives-to-dataframedrop/examples/profile_pd.fillna_alternatives.ipynb

**Comment by Ritunjai-Sharma** [comment]
Hi Jagadish, amazing work! As you mentioned, the only concern with del statement is its in-place modification. I guess this could be an issue if we still need the original dataframe after dropping the required columns (however a workarounds for this is to perhaps store the original dataframe in a temporary dataframe before dropping the columns). However, I had a quick look of where .drop() is being used in tubular using the good old search tab. It does look like whenever .drop is used in tubular, the resultant dataframe is directly being returned. So maybe there's no issue with using del for tubular at all!

If we all agree on this approach of using del, let me know and I'll replace all .drop() occurrences in tubular with del, check if all unit tests are passing and create a PR.

**Comment by limlam96** [comment]
Nice work both. 

Just thinking about whether del could cause problems, possibly if copy was set to False it would update the original df in a way that we didn't want - might be worth writing a test for this scenario? If it fails we can have a think about what to do next!

**Comment by limlam96** [comment]
Sorry RJ didn't see your comment! I think yeah have a go, just also add some tests around whether it causes issues for copy=False, and any other potential problems you can think of :)

**Comment by adamsardar** [comment]
Do note that we're currently looking to remove the copy flag altogether as part of #181 - copy on write will handle how pandas objects are dealt with.

As for updating by reference, users can (and should) create a view:

```python
>>> import pandas as pd

>>> df = pd.DataFrame({"student_id": [1, 2, 3], "grade": ["A", "C", "D"]})
>>> del df['grade']
>>> df
   student_id
0           1
1           2
2           3


>>> df = pd.DataFrame({"student_id": [1, 2, 3], "grade": ["A", "C", "D"]})
>>> df2 = df.iloc[:] # A view of df - no copy is made

>>> del df['grade']
>>> df2
   student_id grade
0           1     A
1           2     C
2           3     D
>>> df
   student_id
0           1
1           2
2           3
```

Pandas knows that the deletion shouldn't propagate to the view - see [docs](https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html#description) on newer versions of pandas

> Previously, when operating on views, the view and the parent object was modified

**Comment by limlam96** [comment]
Given Adam's comment, maybe ignore my comment around testing for copy=False and just make clear in the ChangeLog entry that this release should also remove copy before publishing!
