### ISSUE TITLE
Create generic test class for two column transformers

### ISSUE THREAD

**Issue by limlam96** [lvgig/tubular#204]
What?

Follow the examples in https://github.com/lvgig/tubular/blob/988d3ecdeb31e67e6705ad58f811e355fc308ae0/tests/base_tests.py to create an inheritable base test class for transformers that take just two columns (upper_column and lower_column), the class should contain tests for the handling of invalid values as these arguments.

Why?
Enable the inclusion of two column transformers in the testing refactor

How? 
see what

**Comment by limlam96** [comment]
<del>test</del>

**Comment by limlam96** [comment]
Q: on this, is it worth creating a new arg setup or could we just insist columns be ordered list of strs with len 2?

**Comment by Chip2916** [comment]
Hey Liam - on this why does the arg have to be ordered? In terms of the EqualityChecker this compares whether two columns are equal so don't believe order matters. Is there another transformer that also uses the same arg?

**Comment by limlam96** [comment]
heya Sam - there are some where order will matter, [e.g.](https://github.com/lvgig/tubular/blob/7b8f03e1c0df45e3aecdb2fa698ba3c24d42adb3/tubular/dates.py#L292)

In practice think this shouldn't matter too much as lists are ordered anyway, just docstrings etc should reflect this

**Comment by Chip2916** [comment]
Completed first part of this task as per PR here - https://github.com/lvgig/tubular/pull/240

Suggestion by @limlam96 to create a 'BaseTwoColumnTransformer' class that inherits from BaseTransformer, so will pick that up now

**Comment by Chip2916** [comment]
Second part of ticket completed [here](https://github.com/lvgig/tubular/pull/245) - closed
