### ISSUE TITLE
Refactor date.py

### ISSUE THREAD

**Issue by limlam96** [lvgig/tubular#213]
What?
This collection of transformers needs a bit of a rework before setting up the new testing framework, the classes are set up inconsistently in a way that does not support the new approach.

Suggested actions:

- BaseDateTransformer to implement transform method, that calls check_columns_are_date_or_datetime
- Deprecate cast_columns_to_datetime from BaseDateTransformer, throw error directing to existing ToDatetimeTransformer if columns fail type checks
- Some complications are introduced by transformers checking for datetime OR date type, which allows the possibility of mismatched types across manipulated columns. Suggest we make transformers more opinionated, introduce a type argument that allows date or datetime and checks accordingly. This would allow us to deprecate '_cast_non_matching_columns', 'match_column_datatypes'

Other thoughts:
- We have DateDiffLeapYearTransformer and DateDifferenceTransformer, can these be condensed?

**Comment by davidhopkinson26** [comment]
Consolidating  DateDiffLeapYearTransformer and DateDifferenceTransformer now has its own issue  in #244

**Comment by limlam96** [comment]
Closed with this PR https://github.com/lvgig/tubular/pull/246
