### ISSUE TITLE
[Bug]: DatetimeInfoExtractor prevents pipeline from being saved using joblib or pickle

### ISSUE THREAD

**Issue by Decima2014** [lvgig/tubular#257]
### What happened?

The DatetimeInfoExtractor stores the mappings_provided attribute as a .keys() type. If you try and save a pipeline object which has that pipeline step using joblib or pickle you get an error stating that:

"TypeError: cannot pickle 'dict_keys' object". 

This attribute should be stored as a list instead. We should maybe also add a test that our transformers can be saved as a pickle file

### Environment

scikit-learn == 1.1.3
Python == 3.9.13
joblib == 1.3.2
tubular == 1.1.0

### Relevant error output

```shell
TypeError: cannot pickle 'dict_keys' object
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidhopkinson26** [comment]
Thanks for raising this issue.  Should be a simple fix to switch this to a list and I agree that adding a test we can pickle the objects should be added to generic tests.  the test class base_tests.OtherBaseBehaviourTests was created for this purpose and should be inherited by all transformer test modules.
