### ISSUE TITLE
Narwhalify BaseTransformer

### ISSUE THREAD

**Issue by davidhopkinson26** [lvgig/tubular#313]
**What**

make BaseTransfomer polars compatible while maintaining backwards compatibility with pandas.

**Why?**

Making the project polars compatible for speed benefits.  [Narwhals](https://github.com/narwhals-dev/narwhals) allows us to do this piece by piece and maintain compatibility between components as it makes it possible to pass pandas dataframes to polars logic.  This involves converting between pandas/polars dataframes.  

Without converting parent classes there will be lots of switching back and forth due to calls to super() so we should aim to convert these foundational elements early on.

**How?**

convert logic in BaseTransformer to function with polars dataframes and add [narwhalify decorators](https://github.com/narwhals-dev/narwhals/blob/aaf1eaa2573d585749d175f034584b54c9d5036b/narwhals/translate.py) to methods to ensure compatibility with pandas dataframes.

Update testing where required.  This will require additional tests for polars workflows.

**Comment by limlam96** [comment]
PR https://github.com/lvgig/tubular/pulls
