### ISSUE TITLE
[Bug]: Incorrect link in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by nedwebster** [lvgig/tubular#37]
### What happened?

Broken link in `CONTRIBUTING.rst` document. Specifically the link under the **`General`** section, highlighted in the following line:

`Make sure to update the changelog with details of your change`

This should point to the `CHANGELOG.rst` file, however Error 404 is found. Looking at the raw text, it looks like this points to a `CHANGELOG.rst` file in test-aide.

### Environment

Bug is focused on documentation and is not relevant to a python environment.

### Minimum reproducible code

```shell
N/A
```

### Relevant error output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by davidhopkinson26** [comment]
fixed in [update CONTRIBUTING.rst](https://github.com/lvgig/tubular/pull/64/commits/010560565d24fca84c80c38a3f31aac4772c4c33)
