### ISSUE TITLE
Consistency in columns arguments

### ISSUE THREAD

**Issue by davidhopkinson26** [lvgig/tubular#68]
### The issue:

Most transformers in the package have a `columns: str or list` to pass columns for the transformer to act upon.  Many transformers however have variations on this approach for passing columns. For example `DateDifferenceTransformer` takes  `column_lower : str` and `column_upper : str` arguments,  `CappingTransformer` takes columns as keys in a dictionary of capping values etc.

Some roundabout methods are then being used to make use of the columns checks in 'BaseTransformer` which are potentially confusing.

The inconsistency in inputs across transformers is also arguably not ideal for users.

### Potential solution

`DateDifferenceTransformer` example: 
Refactor to take a  `columns: str or list` argument and treat the first value as column lower and the second as column upper.  debatable if this is more or less user friendly.

`CappingTransformer` example:
refactor dict input to  `columns: str or list` and a list input for the capping values.  This makes it more consistent but might make it harder to read which capping values correspond to which columns.

I'm not convinced that these solutions are more user friendly overall but the issue of inconsistency in inputs has been raised by several users.  Please share opinions on potential changes here.

**Comment by TommyMatthews** [comment]
From the generic testing work, the following transforms can currently only take columns as a list:

[
        'EqualityChecker',
        'InteractionTransformer',
        'TwoColumnOperatorTransformer',
    ]

**Comment by davidhopkinson26** [comment]
Closing and replacing with #150 #151
