### ISSUE TITLE
Remove auto-generated api rst files

### ISSUE THREAD

**Issue by munichpavel** [lvgig/tubular#7]
I believe I accidentally committed these sphinx autodoc files to version control, e.g.  [this commit of docs/source/api/tubular.dates.rst](https://github.com/lvgig/tubular/blob/53e277dea2cc869702f2ed49f2b495bf79b92355/docs/source/api/tubular.dates.rst), which I shouldn't have, since

* they are autogenerated by code under version control
* they are not at all informative

This issue is to remove these files from version control.

@richardangell I am happy to have this one assigned to me :)

**Comment by richardangell** [comment]
this was addressed in https://github.com/lvgig/tubular/pull/22
