### ISSUE TITLE
[Bug]: Tubular not preserving the datatypes

### ISSUE THREAD

**Issue by JagadishSivakumar** [lvgig/tubular#70]
### What happened?

When a downcasted data frame is passed to tubular transformers, the downcasted datatypes are not preserved. The output data frame is returned to its original chunkier datatype.

### Environment

- tubular == 0.3.2
- scikit-learn == 1.0.2
- pandas == 1.1.1
- marshmallow == 3.3.0

### Quick fix 

Additionally, a quick fix to this issue was to pass the downcast features are their datatypes as a custom transformer and apply it in the last stage of the generic pipeline. But other transforms and imputations in the earlier stages of the pipeline are applied to the original chunkier data frame. And then downcasted only at the end and used for training.

### Impact (Memory Consumption)?

Since the tubular transformation and imputations are reverting the features of the data frame to their original dtypes. A vast memory is consumed at the initialisation.

If tubular can preserve the downcasted dtypes of the data frame, the lighter (downcasted) data frame can be used throughout, resulting in faster, efficient run time in production.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidhopkinson26** [comment]
this effect has been confirmed for AritraryImputer but not on other transforms yet.  I expect it applies to all imputers and is a result of inserting a heavier dtype into the column.

Most obvious fix to that would be to read the target column dtype and cast imputer values as that type before imputing.
